version: '3'

services:
  eureka:
      image: anapsix/alpine-java:8_jdk_unlimited
      ports:
        - '8761:8761'
      working_dir: /eureka-server
      volumes:
        - ./eureka-server:/eureka-server
      command: './gradlew bootRun --no-daemon'
      environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
      image: anapsix/alpine-java:8_jdk_unlimited
      ports:
        - '8080:8080'
      working_dir: /api-gateway
      volumes:
        - ./api-gateway:/api-gateway
      depends_on:
        - eureka
      command: './gradlew bootRun --no-daemon'
      environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev
  users-api:
        image: anapsix/alpine-java:8_jdk_unlimited
        ports:
          - '8081:8081'
        working_dir: /users-api
        volumes:
          - ./users-api:/users-api
        depends_on:
          - postgresdev
        command: './gradlew bootRun --no-daemon'
        environment:
          - GRADLE_USER_HOME=cache
          - SPRING_PROFILES_ACTIVE=dev
  # frontend:
  #   image: johnpapa/angular-cli
  #   ports:
  #     - "4200:4200"
  #   working_dir: /frontend
  #   volumes:
  #     - ./frontend:/frontend
  #   command: "npm start"
  postgresdev:
      image: postgres
      ports:
       - "5432:5432"
      environment:
       - POSTGRES_PASSWORD=password
       - POSTGRES_USER=postgres
       - POSTGRES_DB=pgdev
  flyway:
      image: jimmyoak/flyway:4.0.3
      command: "wait-for-it --timeout=30 --strict postgres:5432 -- flyway migrate"
      volumes:
        - './flyway/conf:/flyway/conf'
        - './flyway/sql:/flyway/sql'
